/* AutoGenerated Code, changes may be overwritten
* INPUT GRAMMAR:
* // ─── OBDA Grammar for tsPEG ─────────────────────────────────────────────────
* // Parses the Ontop OBDA mapping file format.
* // Sections: [PrefixDeclaration] and [MappingDeclaration] @collection [[...]]
* obdaFile
*     := _WS sections=section* _WS $
* section
*     := prefixSection
*      | mappingSection
* // ─── Prefix Section ─────────────────────────────────────────────────────────
* prefixSection
*     := header=prefixHeader entries=prefixEntry*
* prefixHeader
*     := _WS '\[PrefixDeclaration\]' _EOL
* prefixEntry
*     := _WS name='[a-zA-Z_][a-zA-Z0-9_]*:' _HTAB+ iri='[^\r\n]+' _EOL
*      | _WS name=':' _HTAB+ iri='[^\r\n]+' _EOL
*      | _BLANKLINE
* // ─── Mapping Section ────────────────────────────────────────────────────────
* // First block can appear without a preceding blank line.
* // Subsequent blocks MUST be separated by at least one blank line.
* mappingSection
*     := _WS '\[MappingDeclaration\]' _SP '@collection' _SP '\[\[' _EOL
*        firstBlock=firstMappingBlock?
*        restBlocks=subsequentMappingBlock*
*        _WS '\]\]' _EOL?
* firstMappingBlock
*     := _BLANKLINE* commentOrBlank* idPart=mappingId targetPart=targetField sourcePart=sourceField
* subsequentMappingBlock
*     := _BLANKLINE+ commentOrBlank* idPart=mappingId targetPart=targetField sourcePart=sourceField
* commentOrBlank
*     := commentLine
*      | _BLANKLINE
* commentLine
*     := '[#;][^\r\n]*' _EOL
* // ─── Mapping Fields ─────────────────────────────────────────────────────────
* mappingId
*     := idPos=@ 'mappingId' _SP+ id='[^\r\n]+' _EOL
* targetField
*     := targetPos=@ 'target' _SP+ targetOffset=@ firstLine='[^\r\n]+' _EOL
*        continuations=targetContinuation*
* targetContinuation
*     := _INDENT offset=@ value='[^\r\n]+' _EOL
* sourceField
*     := sourcePos=@ 'source' _SP+ sourceOffset=@ firstLine='[^\r\n]+' _EOL
*        continuations=sourceContinuation*
* sourceContinuation
*     := _INDENT offset=@ value='[^\r\n]+' _EOL
* // ─── Whitespace Helpers ─────────────────────────────────────────────────────
* _WS       := '[ \t\r\n]*'
* _SP       := '[ \t]'
* _HTAB     := '[ \t]'
* _EOL      := '\r?\n'
*             | $
* _BLANKLINE := '[ \t]*\r?\n'
* _INDENT    := '[ \t][ \t]+'
*               !'mappingId'
*               !'\[MappingDeclaration'
*               !'\[PrefixDeclaration'
*               !'source'
*               !'target'
*               !'[#;]'
*               !'\]\]'
*/
type Nullable<T> = T | null;
type $$RuleType<T> = () => Nullable<T>;
export interface ASTNodeIntf {
    kind: ASTKinds;
}
export enum ASTKinds {
    obdaFile = "obdaFile",
    section_1 = "section_1",
    section_2 = "section_2",
    prefixSection = "prefixSection",
    prefixHeader = "prefixHeader",
    prefixEntry_1 = "prefixEntry_1",
    prefixEntry_2 = "prefixEntry_2",
    prefixEntry_3 = "prefixEntry_3",
    mappingSection = "mappingSection",
    firstMappingBlock = "firstMappingBlock",
    subsequentMappingBlock = "subsequentMappingBlock",
    commentOrBlank_1 = "commentOrBlank_1",
    commentOrBlank_2 = "commentOrBlank_2",
    commentLine = "commentLine",
    mappingId = "mappingId",
    targetField = "targetField",
    targetContinuation = "targetContinuation",
    sourceField = "sourceField",
    sourceContinuation = "sourceContinuation",
    _WS = "_WS",
    _SP = "_SP",
    _HTAB = "_HTAB",
    _EOL_1 = "_EOL_1",
    _EOL_2 = "_EOL_2",
    _BLANKLINE = "_BLANKLINE",
    _INDENT = "_INDENT",
    $EOF = "$EOF",
}
export interface obdaFile {
    kind: ASTKinds.obdaFile;
    sections: section[];
}
export type section = section_1 | section_2;
export type section_1 = prefixSection;
export type section_2 = mappingSection;
export interface prefixSection {
    kind: ASTKinds.prefixSection;
    header: prefixHeader;
    entries: prefixEntry[];
}
export interface prefixHeader {
    kind: ASTKinds.prefixHeader;
}
export type prefixEntry = prefixEntry_1 | prefixEntry_2 | prefixEntry_3;
export interface prefixEntry_1 {
    kind: ASTKinds.prefixEntry_1;
    name: string;
    iri: string;
}
export interface prefixEntry_2 {
    kind: ASTKinds.prefixEntry_2;
    name: string;
    iri: string;
}
export type prefixEntry_3 = _BLANKLINE;
export interface mappingSection {
    kind: ASTKinds.mappingSection;
    firstBlock: Nullable<firstMappingBlock>;
    restBlocks: subsequentMappingBlock[];
}
export interface firstMappingBlock {
    kind: ASTKinds.firstMappingBlock;
    idPart: mappingId;
    targetPart: targetField;
    sourcePart: sourceField;
}
export interface subsequentMappingBlock {
    kind: ASTKinds.subsequentMappingBlock;
    idPart: mappingId;
    targetPart: targetField;
    sourcePart: sourceField;
}
export type commentOrBlank = commentOrBlank_1 | commentOrBlank_2;
export type commentOrBlank_1 = commentLine;
export type commentOrBlank_2 = _BLANKLINE;
export interface commentLine {
    kind: ASTKinds.commentLine;
}
export interface mappingId {
    kind: ASTKinds.mappingId;
    idPos: PosInfo;
    id: string;
}
export interface targetField {
    kind: ASTKinds.targetField;
    targetPos: PosInfo;
    targetOffset: PosInfo;
    firstLine: string;
    continuations: targetContinuation[];
}
export interface targetContinuation {
    kind: ASTKinds.targetContinuation;
    offset: PosInfo;
    value: string;
}
export interface sourceField {
    kind: ASTKinds.sourceField;
    sourcePos: PosInfo;
    sourceOffset: PosInfo;
    firstLine: string;
    continuations: sourceContinuation[];
}
export interface sourceContinuation {
    kind: ASTKinds.sourceContinuation;
    offset: PosInfo;
    value: string;
}
export type _WS = string;
export type _SP = string;
export type _HTAB = string;
export type _EOL = _EOL_1 | _EOL_2;
export type _EOL_1 = string;
export type _EOL_2 = {kind: ASTKinds.$EOF};
export type _BLANKLINE = string;
export interface _INDENT {
    kind: ASTKinds._INDENT;
}
export class Parser {
    private readonly input: string;
    private pos: PosInfo;
    private negating: boolean = false;
    private memoSafe: boolean = true;
    constructor(input: string) {
        this.pos = {overallPos: 0, line: 1, offset: 0};
        this.input = input;
    }
    public reset(pos: PosInfo): void {
        this.pos = pos;
    }
    public finished(): boolean {
        return this.pos.overallPos === this.input.length;
    }
    public clearMemos(): void {
    }
    public matchobdaFile($$dpth: number, $$cr?: ErrorTracker): Nullable<obdaFile> {
        return this.run<obdaFile>($$dpth,
            () => {
                let $scope$sections: Nullable<section[]>;
                let $$res: Nullable<obdaFile> = null;
                if (true
                    && this.match_WS($$dpth + 1, $$cr) !== null
                    && ($scope$sections = this.loop<section>(() => this.matchsection($$dpth + 1, $$cr), 0, -1)) !== null
                    && this.match_WS($$dpth + 1, $$cr) !== null
                    && this.match$EOF($$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.obdaFile, sections: $scope$sections};
                }
                return $$res;
            });
    }
    public matchsection($$dpth: number, $$cr?: ErrorTracker): Nullable<section> {
        return this.choice<section>([
            () => this.matchsection_1($$dpth + 1, $$cr),
            () => this.matchsection_2($$dpth + 1, $$cr),
        ]);
    }
    public matchsection_1($$dpth: number, $$cr?: ErrorTracker): Nullable<section_1> {
        return this.matchprefixSection($$dpth + 1, $$cr);
    }
    public matchsection_2($$dpth: number, $$cr?: ErrorTracker): Nullable<section_2> {
        return this.matchmappingSection($$dpth + 1, $$cr);
    }
    public matchprefixSection($$dpth: number, $$cr?: ErrorTracker): Nullable<prefixSection> {
        return this.run<prefixSection>($$dpth,
            () => {
                let $scope$header: Nullable<prefixHeader>;
                let $scope$entries: Nullable<prefixEntry[]>;
                let $$res: Nullable<prefixSection> = null;
                if (true
                    && ($scope$header = this.matchprefixHeader($$dpth + 1, $$cr)) !== null
                    && ($scope$entries = this.loop<prefixEntry>(() => this.matchprefixEntry($$dpth + 1, $$cr), 0, -1)) !== null
                ) {
                    $$res = {kind: ASTKinds.prefixSection, header: $scope$header, entries: $scope$entries};
                }
                return $$res;
            });
    }
    public matchprefixHeader($$dpth: number, $$cr?: ErrorTracker): Nullable<prefixHeader> {
        return this.run<prefixHeader>($$dpth,
            () => {
                let $$res: Nullable<prefixHeader> = null;
                if (true
                    && this.match_WS($$dpth + 1, $$cr) !== null
                    && this.regexAccept(String.raw`(?:\[PrefixDeclaration\])`, "", $$dpth + 1, $$cr) !== null
                    && this.match_EOL($$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.prefixHeader, };
                }
                return $$res;
            });
    }
    public matchprefixEntry($$dpth: number, $$cr?: ErrorTracker): Nullable<prefixEntry> {
        return this.choice<prefixEntry>([
            () => this.matchprefixEntry_1($$dpth + 1, $$cr),
            () => this.matchprefixEntry_2($$dpth + 1, $$cr),
            () => this.matchprefixEntry_3($$dpth + 1, $$cr),
        ]);
    }
    public matchprefixEntry_1($$dpth: number, $$cr?: ErrorTracker): Nullable<prefixEntry_1> {
        return this.run<prefixEntry_1>($$dpth,
            () => {
                let $scope$name: Nullable<string>;
                let $scope$iri: Nullable<string>;
                let $$res: Nullable<prefixEntry_1> = null;
                if (true
                    && this.match_WS($$dpth + 1, $$cr) !== null
                    && ($scope$name = this.regexAccept(String.raw`(?:[a-zA-Z_][a-zA-Z0-9_]*:)`, "", $$dpth + 1, $$cr)) !== null
                    && this.loopPlus<_HTAB>(() => this.match_HTAB($$dpth + 1, $$cr)) !== null
                    && ($scope$iri = this.regexAccept(String.raw`(?:[^\r\n]+)`, "", $$dpth + 1, $$cr)) !== null
                    && this.match_EOL($$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.prefixEntry_1, name: $scope$name, iri: $scope$iri};
                }
                return $$res;
            });
    }
    public matchprefixEntry_2($$dpth: number, $$cr?: ErrorTracker): Nullable<prefixEntry_2> {
        return this.run<prefixEntry_2>($$dpth,
            () => {
                let $scope$name: Nullable<string>;
                let $scope$iri: Nullable<string>;
                let $$res: Nullable<prefixEntry_2> = null;
                if (true
                    && this.match_WS($$dpth + 1, $$cr) !== null
                    && ($scope$name = this.regexAccept(String.raw`(?::)`, "", $$dpth + 1, $$cr)) !== null
                    && this.loopPlus<_HTAB>(() => this.match_HTAB($$dpth + 1, $$cr)) !== null
                    && ($scope$iri = this.regexAccept(String.raw`(?:[^\r\n]+)`, "", $$dpth + 1, $$cr)) !== null
                    && this.match_EOL($$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.prefixEntry_2, name: $scope$name, iri: $scope$iri};
                }
                return $$res;
            });
    }
    public matchprefixEntry_3($$dpth: number, $$cr?: ErrorTracker): Nullable<prefixEntry_3> {
        return this.match_BLANKLINE($$dpth + 1, $$cr);
    }
    public matchmappingSection($$dpth: number, $$cr?: ErrorTracker): Nullable<mappingSection> {
        return this.run<mappingSection>($$dpth,
            () => {
                let $scope$firstBlock: Nullable<Nullable<firstMappingBlock>>;
                let $scope$restBlocks: Nullable<subsequentMappingBlock[]>;
                let $$res: Nullable<mappingSection> = null;
                if (true
                    && this.match_WS($$dpth + 1, $$cr) !== null
                    && this.regexAccept(String.raw`(?:\[MappingDeclaration\])`, "", $$dpth + 1, $$cr) !== null
                    && this.match_SP($$dpth + 1, $$cr) !== null
                    && this.regexAccept(String.raw`(?:@collection)`, "", $$dpth + 1, $$cr) !== null
                    && this.match_SP($$dpth + 1, $$cr) !== null
                    && this.regexAccept(String.raw`(?:\[\[)`, "", $$dpth + 1, $$cr) !== null
                    && this.match_EOL($$dpth + 1, $$cr) !== null
                    && (($scope$firstBlock = this.matchfirstMappingBlock($$dpth + 1, $$cr)) || true)
                    && ($scope$restBlocks = this.loop<subsequentMappingBlock>(() => this.matchsubsequentMappingBlock($$dpth + 1, $$cr), 0, -1)) !== null
                    && this.match_WS($$dpth + 1, $$cr) !== null
                    && this.regexAccept(String.raw`(?:\]\])`, "", $$dpth + 1, $$cr) !== null
                    && ((this.match_EOL($$dpth + 1, $$cr)) || true)
                ) {
                    $$res = {kind: ASTKinds.mappingSection, firstBlock: $scope$firstBlock, restBlocks: $scope$restBlocks};
                }
                return $$res;
            });
    }
    public matchfirstMappingBlock($$dpth: number, $$cr?: ErrorTracker): Nullable<firstMappingBlock> {
        return this.run<firstMappingBlock>($$dpth,
            () => {
                let $scope$idPart: Nullable<mappingId>;
                let $scope$targetPart: Nullable<targetField>;
                let $scope$sourcePart: Nullable<sourceField>;
                let $$res: Nullable<firstMappingBlock> = null;
                if (true
                    && this.loop<_BLANKLINE>(() => this.match_BLANKLINE($$dpth + 1, $$cr), 0, -1) !== null
                    && this.loop<commentOrBlank>(() => this.matchcommentOrBlank($$dpth + 1, $$cr), 0, -1) !== null
                    && ($scope$idPart = this.matchmappingId($$dpth + 1, $$cr)) !== null
                    && ($scope$targetPart = this.matchtargetField($$dpth + 1, $$cr)) !== null
                    && ($scope$sourcePart = this.matchsourceField($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.firstMappingBlock, idPart: $scope$idPart, targetPart: $scope$targetPart, sourcePart: $scope$sourcePart};
                }
                return $$res;
            });
    }
    public matchsubsequentMappingBlock($$dpth: number, $$cr?: ErrorTracker): Nullable<subsequentMappingBlock> {
        return this.run<subsequentMappingBlock>($$dpth,
            () => {
                let $scope$idPart: Nullable<mappingId>;
                let $scope$targetPart: Nullable<targetField>;
                let $scope$sourcePart: Nullable<sourceField>;
                let $$res: Nullable<subsequentMappingBlock> = null;
                if (true
                    && this.loopPlus<_BLANKLINE>(() => this.match_BLANKLINE($$dpth + 1, $$cr)) !== null
                    && this.loop<commentOrBlank>(() => this.matchcommentOrBlank($$dpth + 1, $$cr), 0, -1) !== null
                    && ($scope$idPart = this.matchmappingId($$dpth + 1, $$cr)) !== null
                    && ($scope$targetPart = this.matchtargetField($$dpth + 1, $$cr)) !== null
                    && ($scope$sourcePart = this.matchsourceField($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.subsequentMappingBlock, idPart: $scope$idPart, targetPart: $scope$targetPart, sourcePart: $scope$sourcePart};
                }
                return $$res;
            });
    }
    public matchcommentOrBlank($$dpth: number, $$cr?: ErrorTracker): Nullable<commentOrBlank> {
        return this.choice<commentOrBlank>([
            () => this.matchcommentOrBlank_1($$dpth + 1, $$cr),
            () => this.matchcommentOrBlank_2($$dpth + 1, $$cr),
        ]);
    }
    public matchcommentOrBlank_1($$dpth: number, $$cr?: ErrorTracker): Nullable<commentOrBlank_1> {
        return this.matchcommentLine($$dpth + 1, $$cr);
    }
    public matchcommentOrBlank_2($$dpth: number, $$cr?: ErrorTracker): Nullable<commentOrBlank_2> {
        return this.match_BLANKLINE($$dpth + 1, $$cr);
    }
    public matchcommentLine($$dpth: number, $$cr?: ErrorTracker): Nullable<commentLine> {
        return this.run<commentLine>($$dpth,
            () => {
                let $$res: Nullable<commentLine> = null;
                if (true
                    && this.regexAccept(String.raw`(?:[#;][^\r\n]*)`, "", $$dpth + 1, $$cr) !== null
                    && this.match_EOL($$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.commentLine, };
                }
                return $$res;
            });
    }
    public matchmappingId($$dpth: number, $$cr?: ErrorTracker): Nullable<mappingId> {
        return this.run<mappingId>($$dpth,
            () => {
                let $scope$idPos: Nullable<PosInfo>;
                let $scope$id: Nullable<string>;
                let $$res: Nullable<mappingId> = null;
                if (true
                    && ($scope$idPos = this.mark()) !== null
                    && this.regexAccept(String.raw`(?:mappingId)`, "", $$dpth + 1, $$cr) !== null
                    && this.loopPlus<_SP>(() => this.match_SP($$dpth + 1, $$cr)) !== null
                    && ($scope$id = this.regexAccept(String.raw`(?:[^\r\n]+)`, "", $$dpth + 1, $$cr)) !== null
                    && this.match_EOL($$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.mappingId, idPos: $scope$idPos, id: $scope$id};
                }
                return $$res;
            });
    }
    public matchtargetField($$dpth: number, $$cr?: ErrorTracker): Nullable<targetField> {
        return this.run<targetField>($$dpth,
            () => {
                let $scope$targetPos: Nullable<PosInfo>;
                let $scope$targetOffset: Nullable<PosInfo>;
                let $scope$firstLine: Nullable<string>;
                let $scope$continuations: Nullable<targetContinuation[]>;
                let $$res: Nullable<targetField> = null;
                if (true
                    && ($scope$targetPos = this.mark()) !== null
                    && this.regexAccept(String.raw`(?:target)`, "", $$dpth + 1, $$cr) !== null
                    && this.loopPlus<_SP>(() => this.match_SP($$dpth + 1, $$cr)) !== null
                    && ($scope$targetOffset = this.mark()) !== null
                    && ($scope$firstLine = this.regexAccept(String.raw`(?:[^\r\n]+)`, "", $$dpth + 1, $$cr)) !== null
                    && this.match_EOL($$dpth + 1, $$cr) !== null
                    && ($scope$continuations = this.loop<targetContinuation>(() => this.matchtargetContinuation($$dpth + 1, $$cr), 0, -1)) !== null
                ) {
                    $$res = {kind: ASTKinds.targetField, targetPos: $scope$targetPos, targetOffset: $scope$targetOffset, firstLine: $scope$firstLine, continuations: $scope$continuations};
                }
                return $$res;
            });
    }
    public matchtargetContinuation($$dpth: number, $$cr?: ErrorTracker): Nullable<targetContinuation> {
        return this.run<targetContinuation>($$dpth,
            () => {
                let $scope$offset: Nullable<PosInfo>;
                let $scope$value: Nullable<string>;
                let $$res: Nullable<targetContinuation> = null;
                if (true
                    && this.match_INDENT($$dpth + 1, $$cr) !== null
                    && ($scope$offset = this.mark()) !== null
                    && ($scope$value = this.regexAccept(String.raw`(?:[^\r\n]+)`, "", $$dpth + 1, $$cr)) !== null
                    && this.match_EOL($$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.targetContinuation, offset: $scope$offset, value: $scope$value};
                }
                return $$res;
            });
    }
    public matchsourceField($$dpth: number, $$cr?: ErrorTracker): Nullable<sourceField> {
        return this.run<sourceField>($$dpth,
            () => {
                let $scope$sourcePos: Nullable<PosInfo>;
                let $scope$sourceOffset: Nullable<PosInfo>;
                let $scope$firstLine: Nullable<string>;
                let $scope$continuations: Nullable<sourceContinuation[]>;
                let $$res: Nullable<sourceField> = null;
                if (true
                    && ($scope$sourcePos = this.mark()) !== null
                    && this.regexAccept(String.raw`(?:source)`, "", $$dpth + 1, $$cr) !== null
                    && this.loopPlus<_SP>(() => this.match_SP($$dpth + 1, $$cr)) !== null
                    && ($scope$sourceOffset = this.mark()) !== null
                    && ($scope$firstLine = this.regexAccept(String.raw`(?:[^\r\n]+)`, "", $$dpth + 1, $$cr)) !== null
                    && this.match_EOL($$dpth + 1, $$cr) !== null
                    && ($scope$continuations = this.loop<sourceContinuation>(() => this.matchsourceContinuation($$dpth + 1, $$cr), 0, -1)) !== null
                ) {
                    $$res = {kind: ASTKinds.sourceField, sourcePos: $scope$sourcePos, sourceOffset: $scope$sourceOffset, firstLine: $scope$firstLine, continuations: $scope$continuations};
                }
                return $$res;
            });
    }
    public matchsourceContinuation($$dpth: number, $$cr?: ErrorTracker): Nullable<sourceContinuation> {
        return this.run<sourceContinuation>($$dpth,
            () => {
                let $scope$offset: Nullable<PosInfo>;
                let $scope$value: Nullable<string>;
                let $$res: Nullable<sourceContinuation> = null;
                if (true
                    && this.match_INDENT($$dpth + 1, $$cr) !== null
                    && ($scope$offset = this.mark()) !== null
                    && ($scope$value = this.regexAccept(String.raw`(?:[^\r\n]+)`, "", $$dpth + 1, $$cr)) !== null
                    && this.match_EOL($$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.sourceContinuation, offset: $scope$offset, value: $scope$value};
                }
                return $$res;
            });
    }
    public match_WS($$dpth: number, $$cr?: ErrorTracker): Nullable<_WS> {
        return this.regexAccept(String.raw`(?:[ \t\r\n]*)`, "", $$dpth + 1, $$cr);
    }
    public match_SP($$dpth: number, $$cr?: ErrorTracker): Nullable<_SP> {
        return this.regexAccept(String.raw`(?:[ \t])`, "", $$dpth + 1, $$cr);
    }
    public match_HTAB($$dpth: number, $$cr?: ErrorTracker): Nullable<_HTAB> {
        return this.regexAccept(String.raw`(?:[ \t])`, "", $$dpth + 1, $$cr);
    }
    public match_EOL($$dpth: number, $$cr?: ErrorTracker): Nullable<_EOL> {
        return this.choice<_EOL>([
            () => this.match_EOL_1($$dpth + 1, $$cr),
            () => this.match_EOL_2($$dpth + 1, $$cr),
        ]);
    }
    public match_EOL_1($$dpth: number, $$cr?: ErrorTracker): Nullable<_EOL_1> {
        return this.regexAccept(String.raw`(?:\r?\n)`, "", $$dpth + 1, $$cr);
    }
    public match_EOL_2($$dpth: number, $$cr?: ErrorTracker): Nullable<_EOL_2> {
        return this.match$EOF($$cr);
    }
    public match_BLANKLINE($$dpth: number, $$cr?: ErrorTracker): Nullable<_BLANKLINE> {
        return this.regexAccept(String.raw`(?:[ \t]*\r?\n)`, "", $$dpth + 1, $$cr);
    }
    public match_INDENT($$dpth: number, $$cr?: ErrorTracker): Nullable<_INDENT> {
        return this.run<_INDENT>($$dpth,
            () => {
                let $$res: Nullable<_INDENT> = null;
                if (true
                    && this.regexAccept(String.raw`(?:[ \t][ \t]+)`, "", $$dpth + 1, $$cr) !== null
                    && this.negate(() => this.regexAccept(String.raw`(?:mappingId)`, "", $$dpth + 1, $$cr)) !== null
                    && this.negate(() => this.regexAccept(String.raw`(?:\[MappingDeclaration)`, "", $$dpth + 1, $$cr)) !== null
                    && this.negate(() => this.regexAccept(String.raw`(?:\[PrefixDeclaration)`, "", $$dpth + 1, $$cr)) !== null
                    && this.negate(() => this.regexAccept(String.raw`(?:source)`, "", $$dpth + 1, $$cr)) !== null
                    && this.negate(() => this.regexAccept(String.raw`(?:target)`, "", $$dpth + 1, $$cr)) !== null
                    && this.negate(() => this.regexAccept(String.raw`(?:[#;])`, "", $$dpth + 1, $$cr)) !== null
                    && this.negate(() => this.regexAccept(String.raw`(?:\]\])`, "", $$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds._INDENT, };
                }
                return $$res;
            });
    }
    public test(): boolean {
        const mrk = this.mark();
        const res = this.matchobdaFile(0);
        const ans = res !== null;
        this.reset(mrk);
        return ans;
    }
    public parse(): ParseResult {
        const mrk = this.mark();
        const res = this.matchobdaFile(0);
        if (res)
            return {ast: res, errs: []};
        this.reset(mrk);
        const rec = new ErrorTracker();
        this.clearMemos();
        this.matchobdaFile(0, rec);
        const err = rec.getErr()
        return {ast: res, errs: err !== null ? [err] : []}
    }
    public mark(): PosInfo {
        return this.pos;
    }
    // @ts-ignore: loopPlus may not be called
    private loopPlus<T>(func: $$RuleType<T>): Nullable<[T, ...T[]]> {
        return this.loop(func, 1, -1) as Nullable<[T, ...T[]]>;
    }
    private loop<T>(func: $$RuleType<T>, lb: number, ub: number): Nullable<T[]> {
        const mrk = this.mark();
        const res: T[] = [];
        while (ub === -1 || res.length < ub) {
            const preMrk = this.mark();
            const t = func();
            if (t === null || this.pos.overallPos === preMrk.overallPos) {
                break;
            }
            res.push(t);
        }
        if (res.length >= lb) {
            return res;
        }
        this.reset(mrk);
        return null;
    }
    private run<T>($$dpth: number, fn: $$RuleType<T>): Nullable<T> {
        const mrk = this.mark();
        const res = fn()
        if (res !== null)
            return res;
        this.reset(mrk);
        return null;
    }
    // @ts-ignore: choice may not be called
    private choice<T>(fns: Array<$$RuleType<T>>): Nullable<T> {
        for (const f of fns) {
            const res = f();
            if (res !== null) {
                return res;
            }
        }
        return null;
    }
    private regexAccept(match: string, mods: string, dpth: number, cr?: ErrorTracker): Nullable<string> {
        return this.run<string>(dpth,
            () => {
                const reg = new RegExp(match, "y" + mods);
                const mrk = this.mark();
                reg.lastIndex = mrk.overallPos;
                const res = this.tryConsume(reg);
                if(cr) {
                    cr.record(mrk, res, {
                        kind: "RegexMatch",
                        // We substring from 3 to len - 1 to strip off the
                        // non-capture group syntax added as a WebKit workaround
                        literal: match.substring(3, match.length - 1),
                        negated: this.negating,
                    });
                }
                return res;
            });
    }
    private tryConsume(reg: RegExp): Nullable<string> {
        const res = reg.exec(this.input);
        if (res) {
            let lineJmp = 0;
            let lind = -1;
            for (let i = 0; i < res[0].length; ++i) {
                if (res[0][i] === "\n") {
                    ++lineJmp;
                    lind = i;
                }
            }
            this.pos = {
                overallPos: reg.lastIndex,
                line: this.pos.line + lineJmp,
                offset: lind === -1 ? this.pos.offset + res[0].length : (res[0].length - lind - 1)
            };
            return res[0];
        }
        return null;
    }
    // @ts-ignore: noConsume may not be called
    private noConsume<T>(fn: $$RuleType<T>): Nullable<T> {
        const mrk = this.mark();
        const res = fn();
        this.reset(mrk);
        return res;
    }
    // @ts-ignore: negate may not be called
    private negate<T>(fn: $$RuleType<T>): Nullable<boolean> {
        const mrk = this.mark();
        const oneg = this.negating;
        this.negating = !oneg;
        const res = fn();
        this.negating = oneg;
        this.reset(mrk);
        return res === null ? true : null;
    }
    // @ts-ignore: Memoise may not be used
    private memoise<K>(rule: $$RuleType<K>, memo: Map<number, [Nullable<K>, PosInfo]>): Nullable<K> {
        const $scope$pos = this.mark();
        const $scope$memoRes = memo.get($scope$pos.overallPos);
        if(this.memoSafe && $scope$memoRes !== undefined) {
        this.reset($scope$memoRes[1]);
        return $scope$memoRes[0];
        }
        const $scope$result = rule();
        if(this.memoSafe)
        memo.set($scope$pos.overallPos, [$scope$result, this.mark()]);
        return $scope$result;
    }
    private match$EOF(et?: ErrorTracker): Nullable<{kind: ASTKinds.$EOF}> {
        const res: {kind: ASTKinds.$EOF} | null = this.finished() ? { kind: ASTKinds.$EOF } : null;
        if(et)
            et.record(this.mark(), res, { kind: "EOF", negated: this.negating });
        return res;
    }
}
export function parse(s: string): ParseResult {
    const p = new Parser(s);
    return p.parse();
}
export interface ParseResult {
    ast: Nullable<obdaFile>;
    errs: SyntaxErr[];
}
export interface PosInfo {
    readonly overallPos: number;
    readonly line: number;
    readonly offset: number;
}
export interface RegexMatch {
    readonly kind: "RegexMatch";
    readonly negated: boolean;
    readonly literal: string;
}
export type EOFMatch = { kind: "EOF"; negated: boolean };
export type MatchAttempt = RegexMatch | EOFMatch;
export class SyntaxErr {
    public pos: PosInfo;
    public expmatches: MatchAttempt[];
    constructor(pos: PosInfo, expmatches: MatchAttempt[]) {
        this.pos = pos;
        this.expmatches = [...expmatches];
    }
    public toString(): string {
        return `Syntax Error at line ${this.pos.line}:${this.pos.offset}. Expected one of ${this.expmatches.map(x => x.kind === "EOF" ? " EOF" : ` ${x.negated ? 'not ': ''}'${x.literal}'`)}`;
    }
}
class ErrorTracker {
    private mxpos: PosInfo = {overallPos: -1, line: -1, offset: -1};
    private regexset: Set<string> = new Set();
    private pmatches: MatchAttempt[] = [];
    public record(pos: PosInfo, result: any, att: MatchAttempt): void {
        if ((result === null) === att.negated)
            return;
        if (pos.overallPos > this.mxpos.overallPos) {
            this.mxpos = pos;
            this.pmatches = [];
            this.regexset.clear()
        }
        if (this.mxpos.overallPos === pos.overallPos) {
            if(att.kind === "RegexMatch") {
                if(!this.regexset.has(att.literal))
                    this.pmatches.push(att);
                this.regexset.add(att.literal);
            } else {
                this.pmatches.push(att);
            }
        }
    }
    public getErr(): SyntaxErr | null {
        if (this.mxpos.overallPos !== -1)
            return new SyntaxErr(this.mxpos, this.pmatches);
        return null;
    }
}